M48
; DRILL file {KiCad 7.0.8} date Mon Oct 16 16:32:14 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-16T16:32:14-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.1181
%
G90
G05
T1
X3.8Y-2.3
X3.8Y-2.5
X3.9Y-2.6
X3.9Y-2.7
X4.0Y-3.2
X4.3Y-2.6
X4.3Y-3.1
T2
X4.4016Y-2.6
X4.5Y-2.6
T3
X3.5Y-3.5
T0
M30
